#
  # Copyright 2021 ZUP IT SERVICOS EM TECNOLOGIA E INOVACAO SA
  #
  # Licensed under the Apache License, Version 2.0 (the "License");
  # you may not use this file except in compliance with the License.
  # You may obtain a copy of the License at
  #
  #  http://www.apache.org/licenses/LICENSE-2.0
  #
  # Unless required by applicable law or agreed to in writing, software
  # distributed under the License is distributed on an "AS IS" BASIS,
  # WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
  # See the License for the specific language governing permissions and
  # limitations under the License.
#
name: PreDoc

on:
  push:
    branches: [ main ]

jobs:
  predoc_deploy_c4model:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f #v2.3.4
        with:
          submodules: true
          fetch-depth: 0

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@0d9a5be0dceea74e09396820e1e522ba4a110d2f #v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID_DEV }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_DEV }}
          aws-region: ${{ secrets.AWS_REGION_DEV }}
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME_DEV }}
          role-duration-seconds: 1200
          role-session-name: PreDocS3Session
          role-skip-session-tagging: true

      - name: Remove Custom C4Builder Assets from S3
        run: aws s3 rm s3://${{ secrets.AWS_S3_BUCKET_DEV }}/c4model/assets/ --recursive
    
      - name: Upload Custom C4Builder Assets CSS on S3
        run: aws s3 sync --follow-symlinks assets/ s3://${{ secrets.AWS_S3_BUCKET_DEV }}/c4model/assets/  

      - name: C4Builder PT-BR
        uses: ZupIT/c4builder-action@880d2639f0e8a7cf2b05452111fb8d741a4e5651 #v1.0.3
        with:
          path: 'pt-br'

      - name: Upload PT-BR on S3
        run: aws s3 sync --follow-symlinks pt-br/docs s3://${{ secrets.AWS_S3_BUCKET_DEV }}/c4model/pt-br/ --delete

      - name: C4Builder EN
        uses: ZupIT/c4builder-action@880d2639f0e8a7cf2b05452111fb8d741a4e5651 #v1.0.3
        with:
          path: 'en'  

      - name: Upload EN on S3
        run: aws s3 sync --follow-symlinks en/docs s3://${{ secrets.AWS_S3_BUCKET_DEV }}/c4model/en/ --delete

 